#!/usr/bin/env node
// Icon-pack curation for FigureLab — DEV ONLY, never shipped in the HTML.
//
// FigureLab's own icons are drawn in-file and MIT-licensed with the app. This tool is
// for importing third-party packs (Bioicons, NIH BioArt) without importing a licensing
// problem: it filters by licence, rejects share-alike outright, requires attribution
// metadata where the licence demands it, and emits a paste-ready block.
//
// It deliberately does NOT write into figure_lab.html. A human reviews the emitted
// block — both the artwork and the licence claims — and pastes it in. Automating that
// step would mean shipping art nobody looked at.
//
//   node tools/build-icons.mjs --manifest tools/pack.json --out tools/out.js
//
// The manifest is a list of {url, name, label, group, keys, license:{spdx,author,src}}.
// Building it is the curation work; this script is the mechanical part.

import fs from 'node:fs/promises';

// Mirrors ICON_LICENSES_ALLOWED in figure_lab.html. A test in tests/v312.spec.js
// asserts the app never contains anything outside this set, so the two cannot drift
// without something going red.
const ALLOWED   = ['CC0-1.0', 'MIT', 'CC-BY-3.0', 'CC-BY-4.0', 'public-domain'];
const NEEDS_ATTR = ['CC-BY-3.0', 'CC-BY-4.0'];
// Share-alike is excluded on purpose: it can be read as reaching the figure the icon is
// placed into, which is not a risk to hand an author about to submit a manuscript.
const REJECTED  = ['CC-BY-SA-3.0', 'CC-BY-SA-4.0', 'GPL-3.0', 'CC-BY-NC-4.0'];

const BUDGET_BYTES = 400 * 1024;   // the whole pack, inlined

const arg = (n, d) => {
  const i = process.argv.indexOf(n);
  return i > -1 ? process.argv[i + 1] : d;
};

/** Strip an SVG down to what FigureLab can recolour and inline. */
function normalise(svg, key = '#222222') {
  let s = svg
    .replace(/<\?xml[\s\S]*?\?>/g, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/<(metadata|title|desc)[\s\S]*?<\/\1>/g, '')
    .replace(/\s+(id|class|data-[\w-]+)="[^"]*"/g, '')
    .replace(/\s{2,}/g, ' ')
    .trim();
  // FigureLab recolours by substituting a sentinel colour, so every explicit fill or
  // stroke has to become that sentinel. Anything left as a literal colour would ignore
  // the colour picker and quietly look wrong next to the rest of the figure.
  s = s.replace(/(fill|stroke)="(?!none)[^"]*"/g, `$1="${key}"`)
       .replace(/currentColor/g, key);
  return s;
}

async function main() {
  const manifestPath = arg('--manifest');
  const outPath = arg('--out', 'tools/out.js');
  if (!manifestPath) {
    console.error('usage: node tools/build-icons.mjs --manifest <file.json> [--out <file.js>]');
    process.exit(2);
  }
  const manifest = JSON.parse(await fs.readFile(manifestPath, 'utf8'));

  const kept = [], skipped = [];
  for (const item of manifest) {
    const spdx = item.license?.spdx;
    if (REJECTED.includes(spdx)) { skipped.push([item.name, `rejected licence ${spdx}`]); continue; }
    if (!ALLOWED.includes(spdx)) { skipped.push([item.name, `unknown licence ${spdx || '(none)'}`]); continue; }
    // A CC-BY icon without an author cannot be attributed, so it cannot be used.
    if (NEEDS_ATTR.includes(spdx) && !(item.license.author && item.license.src)) {
      skipped.push([item.name, `${spdx} needs license.author and license.src`]); continue;
    }
    let svg;
    try {
      const r = await fetch(item.url);
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      svg = normalise(await r.text());
    } catch (e) { skipped.push([item.name, `fetch failed: ${e.message}`]); continue; }
    if (svg.length > 4096) { skipped.push([item.name, `too large after cleanup (${svg.length}B)`]); continue; }
    kept.push({ ...item, svg });
  }

  const lines = kept.map(i =>
    `  ${i.name}:{label:${JSON.stringify(i.label)},group:${JSON.stringify(i.group)},` +
    `keys:${JSON.stringify(i.keys || '')},w:${i.w || 100},h:${i.h || 100},` +
    `lic:${JSON.stringify(i.license)},svg:${JSON.stringify(i.svg)}},`);

  const block =
    `// ═══ ICON PACK (generated by tools/build-icons.mjs — do not hand-edit) ═══\n` +
    `// Reviewed on import: every entry declares its own licence, and the licence is in\n` +
    `// the app's allowlist. Attribution-required icons carry author + source, which the\n` +
    `// Credits panel turns into a paste-ready line.\n` +
    `Object.assign(SCIENCE_ICONS, {\n${lines.join('\n')}\n});\n`;

  await fs.writeFile(outPath, block, 'utf8');

  const bytes = Buffer.byteLength(block, 'utf8');
  console.log(`kept ${kept.length}, skipped ${skipped.length}`);
  for (const [n, why] of skipped) console.log(`  skip ${n}: ${why}`);
  console.log(`\n${outPath}: ${(bytes / 1024).toFixed(1)} KB of ${(BUDGET_BYTES / 1024)} KB budget`);
  if (bytes > BUDGET_BYTES) {
    console.error('OVER BUDGET — trim the manifest before pasting this in.');
    process.exit(1);
  }
  console.log('Review the artwork and the licence claims, then paste into figure_lab.html.');
}

main().catch(e => { console.error(e); process.exit(1); });
